#!/bin/bash
# Full Network Reconnaissance Script
# Author: Thierry Braga

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Banner
echo -e "${BLUE}"
cat << "EOF"
╔═══════════════════════════════════════════════════════════╗
║           FULL NETWORK RECONNAISSANCE                     ║
║           Automated Pentest Workflow                      ║
╚═══════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

# Check arguments
if [ $# -lt 1 ]; then
    echo -e "${RED}Usage: $0 <target> [output_dir]${NC}"
    echo -e "Example: $0 192.168.1.0/24 /root/reports/recon_2024"
    exit 1
fi

TARGET=$1
OUTPUT_DIR=${2:-"/root/reports/recon_$(date +%Y%m%d_%H%M%S)"}

# Create output directory
mkdir -p "$OUTPUT_DIR"/{nmap,masscan,screenshots,vulnerabilities}

echo -e "${GREEN}[+] Target: $TARGET${NC}"
echo -e "${GREEN}[+] Output Directory: $OUTPUT_DIR${NC}"
echo ""

# Phase 1: Host Discovery
echo -e "${YELLOW}[*] Phase 1: Host Discovery${NC}"
echo -e "${BLUE}[*] Running nmap ping scan...${NC}"
nmap -sn $TARGET -oA "$OUTPUT_DIR/nmap/host_discovery" | tee "$OUTPUT_DIR/host_discovery.txt"

# Extract live hosts
LIVE_HOSTS=$(grep "Nmap scan report" "$OUTPUT_DIR/host_discovery.txt" | awk '{print $5}')
echo -e "${GREEN}[+] Found $(echo "$LIVE_HOSTS" | wc -l) live hosts${NC}"
echo "$LIVE_HOSTS" > "$OUTPUT_DIR/live_hosts.txt"

# Phase 2: Port Scanning
echo -e "\n${YELLOW}[*] Phase 2: Port Scanning${NC}"
echo -e "${BLUE}[*] Running masscan for quick port discovery...${NC}"
masscan $TARGET -p1-65535 --rate=1000 -oL "$OUTPUT_DIR/masscan/all_ports.txt"

# Phase 3: Service Detection
echo -e "\n${YELLOW}[*] Phase 3: Service Version Detection${NC}"
for host in $LIVE_HOSTS; do
    echo -e "${BLUE}[*] Scanning $host...${NC}"
    nmap -sV -sC -O -A -p- $host -oA "$OUTPUT_DIR/nmap/${host}_full" &
done
wait

# Phase 4: Vulnerability Scanning
echo -e "\n${YELLOW}[*] Phase 4: Vulnerability Scanning${NC}"
for host in $LIVE_HOSTS; do
    echo -e "${BLUE}[*] Running vulnerability scripts on $host...${NC}"
    nmap --script vuln -p- $host -oA "$OUTPUT_DIR/vulnerabilities/${host}_vulns" &
done
wait

# Phase 5: Web Service Enumeration
echo -e "\n${YELLOW}[*] Phase 5: Web Service Enumeration${NC}"
for host in $LIVE_HOSTS; do
    # Check for HTTP/HTTPS
    if grep -q "80/tcp.*http" "$OUTPUT_DIR/nmap/${host}_full.nmap" 2>/dev/null; then
        echo -e "${BLUE}[*] Running nikto on http://$host${NC}"
        nikto -h http://$host -o "$OUTPUT_DIR/vulnerabilities/${host}_nikto_80.txt" &
    fi
    
    if grep -q "443/tcp.*https" "$OUTPUT_DIR/nmap/${host}_full.nmap" 2>/dev/null; then
        echo -e "${BLUE}[*] Running nikto on https://$host${NC}"
        nikto -h https://$host -ssl -o "$OUTPUT_DIR/vulnerabilities/${host}_nikto_443.txt" &
    fi
done
wait

# Phase 6: Generate Summary Report
echo -e "\n${YELLOW}[*] Phase 6: Generating Summary Report${NC}"
REPORT_FILE="$OUTPUT_DIR/SUMMARY_REPORT.txt"

cat > "$REPORT_FILE" << EOF
╔═══════════════════════════════════════════════════════════╗
║           NETWORK RECONNAISSANCE REPORT                   ║
╚═══════════════════════════════════════════════════════════╝

Target: $TARGET
Date: $(date)
Analyst: $(whoami)

═══════════════════════════════════════════════════════════

1. LIVE HOSTS ($(echo "$LIVE_HOSTS" | wc -l) found)
─────────────────────────────────────────────────────────
EOF

echo "$LIVE_HOSTS" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << EOF

═══════════════════════════════════════════════════════════

2. OPEN PORTS SUMMARY
─────────────────────────────────────────────────────────
EOF

for host in $LIVE_HOSTS; do
    if [ -f "$OUTPUT_DIR/nmap/${host}_full.nmap" ]; then
        echo "" >> "$REPORT_FILE"
        echo "Host: $host" >> "$REPORT_FILE"
        echo "─────────────────────────────────────────────────────────" >> "$REPORT_FILE"
        grep "open" "$OUTPUT_DIR/nmap/${host}_full.nmap" | head -20 >> "$REPORT_FILE"
    fi
done

cat >> "$REPORT_FILE" << EOF

═══════════════════════════════════════════════════════════

3. POTENTIAL VULNERABILITIES
─────────────────────────────────────────────────────────
EOF

for vulnfile in "$OUTPUT_DIR/vulnerabilities"/*_vulns.nmap; do
    if [ -f "$vulnfile" ]; then
        echo "" >> "$REPORT_FILE"
        basename "$vulnfile" >> "$REPORT_FILE"
        grep -i "VULNERABLE\|CVE" "$vulnfile" | head -10 >> "$REPORT_FILE"
    fi
done

cat >> "$REPORT_FILE" << EOF

═══════════════════════════════════════════════════════════

END OF REPORT
Generated by: Kali Linux MCP Pentest Environment
═══════════════════════════════════════════════════════════
EOF

# Final summary
echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║           RECONNAISSANCE COMPLETE                         ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}[+] Live Hosts: $(echo "$LIVE_HOSTS" | wc -l)${NC}"
echo -e "${GREEN}[+] Output Directory: $OUTPUT_DIR${NC}"
echo -e "${GREEN}[+] Summary Report: $REPORT_FILE${NC}"
echo ""
echo -e "${BLUE}[*] Next Steps:${NC}"
echo -e "    1. Review summary report: cat $REPORT_FILE"
echo -e "    2. Analyze detailed nmap results"
echo -e "    3. Investigate vulnerabilities"
echo -e "    4. Plan exploitation strategy"
echo ""
